#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  - sudo usermod -aG docker ubuntu
  - sudo systemctl enable docker
  - sudo systemctl start docker
  - sudo docker pull containrrr/watchtower
  - sudo docker pull nchopyk/simple_web_app:latest
  - sudo docker run -d -p 80:80 nchopyk/simple_web_app:latest
  - sudo docker run -d --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --interval 30
